export const DASHBAORD = '[Dashboard]';

export const DEFAULT_ACTION = `${DASHBAORD} DEFAULT_ACTION`;

export const FETCH_IMAGE_REQUEST = `${DASHBAORD} FETCH_IMAGE_REQUEST`;
export const FETCH_IMAGE_REQUEST_SUCCESS = `${DASHBAORD} FETCH_IMAGE_REQUEST_SUCCESS`;

